name: CI

on:
  workflow_dispatch:
  push:
  pull_request:

permissions: {}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          
      - name: Set up Python 3.11.6
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.6"

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies with uv
        run: |
          uv sync

      - name: Run pre-commit
        uses: tox-dev/action-pre-commit-uv@v1
